# MIT License

# Copyright (c) 2025 Jisang Yun

version: '3'
services:
  sim:
    image: ros2_docker_env
    build: ./
    volumes: 
      - ./:/ros2_docker_ws
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true 
  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
